### PR TITLE
Remove useless var

### PR DESCRIPTION
**Pull request by alkabal**

### CODE REVIEW

**Comment by kiall** [comment]
Thanks! I must have left these in by mistake :)

**Comment by alkabal** [comment]
Lol it does bug nothing but make more difficult for understand your process 

Did you plan to move other value in your system ? (probe.ps_probe_latch)
Imo for the moment the use of _psng_probe_x.ngc can be removed easily sending [var axis] from first call but if you plan to add other things inside I understand the use.

**Comment by kiall** [comment]
> Did you plan to move other value in your system ? (probe.ps_probe_latch)

I'm not sure I understand?

> Imo for the moment the use of _psng_probe_x.ngc can be removed easily sending [var axis] from first call but if you plan to add other things inside I understand the use.

The `_psng_probe_x/y/z.ngc` files are just there so the 1/2/3 don't need to be spread all over the code - It's much easier to read a call to  `_psng_probe_z` and know exactly what it's going to do, vs `_psng_probe [3]` and having to remember that `3` means `Z`. I wish LinuxCNC supported passing string values as arguments, which would make it far easier - but it doesn't - so we're left with assigning "magic numbers" and wherever possible, we should limit/contain their use as much as possible.

https://en.wikipedia.org/wiki/Magic_number_(programming)

**Comment by alkabal** [comment]
I understand now thanks a lot for the information 

> Did you plan to move other value in your system ? (probe.ps_probe_latch)

I ask that because after used many time playing with the autolenght and tool diameter I’m convinced we need to use différents value from ini file for all the toolsetter concerned move.

This component mix 2 stuff, probing and tooling and imo the GUI settings need to be only for probing stuff.

Imo the toolsetter concerned code need to be close as possible to the standard Linuxcnc behavior. Using [EMCIO] value, At_G30, quill_up

Br

**Comment by kiall** [comment]
> I understand now thanks a lot for the information
> Did you plan to move other value in your system ? (probe.ps_probe_latch)
> I ask that because after used many time playing with the autolenght and tool diameter I’m convinced we need to use différents value from ini file for all the toolsetter concerned move. This component mix 2 stuff, probing and tooling and imo the GUI settings need to be only for probing stuff.

`ps_probe_latch` is just the distance to back off, if it's set large enough that the probe/setter inputs clear, it should work with a single value? Can you provide more detail in a new issue if this isn't the case with your setup?

> Imo the toolsetter concerned code need to be close as possible to the standard Linuxcnc behavior. Using [EMCIO] value, At_G30, quill_up Br

Agreed - but migrating to those (to me) feels like less of a priority than making things reliable & maintainable - once everything's at a point that it works, the code is understandable, etc etc, then it's time IMO to add features or replace features with built in stuff.

**Comment by alkabal** [comment]
I understand your opinion, but at the inverse for now I have mostly play with this.

The most problem imo is the settings can be changed on the fly for pro tans this is very good for that ! But tooling I think need some different fixed value for working fine in all situation.

Also I have do the change for use in all macro G38.5 if setting reverse_latche is not 0 and particularly with these stuff and also with tool diameter I have finally replace all the setting for use from ini

**Comment by alkabal** [comment]
```
#******************************************
[PROBE_SCREEN]
# Allow user to define the toolnumber for probe (need to be in the tooltable)
PROBE_NUMBER = 999
# Speed of movements during working in Probe Screen
RAPID_SPEED = 400
# Latched distance after probing use value like 1mm for standalone
# or something like 0.3mm is enough if you use REVERSE_LATCH
PROBE_LATCH = 0.3
# If probe as spring touch you can use REVERSE_LATCH with G38.5 with value like 1mm
# or 0 if your setter does not have a spring inside (inhibit G38.5)
PROBE_REVERSE_LATCH = 0


[TOOLSENSOR]
# Absolute coordinates of the toolsetter pad G53 machine cooordinates
X = -40
Y = -40
# Absolute Z start search coordinates move relative G0 from toolchange position
Z = -30

# Maximum search distance and direction (sign)
TS_MAXPROBE = -80

# Fast first probe tool velocity
TS_SEARCH_VEL = 300

# Slow final probe velocity
TS_PROBE_VEL = 10

# ADDED FOR ATTEMPT FULL PYTHON REMAP.
TS_HEIGHT = 40

# Separated from regular GUI for keep GUI setting for probe
TS_CLEARANCE = 3

# Latched distance after probing use value like 1mm for standalone
# or something like 0.3mm is enough if you use REVERSE_LATCH
TS_LATCH = 0.3

# If setter as spring inside you can use REVERSE_LATCH with G38.5 with value like 1mm
# or 0 if your setter does not have a spring inside (inhibit G38.5)
TS_REVERSE_LATCH = 2

# Diameter of toolsetter pad
TS_DIAMETER = 10

# offset to add from touching toolsetter pad to signal triggering
TS_DIAM_OFFSET = 0.14

# The speed of the reverse rotation of the spindle when measuring the tool diameter
TS_REV_ROT_SPEED = 300

```

**Comment by alkabal** [comment]
also moved the rapid_speed from toolsensor to probe_screen seem to be more logic for me

**Pull request merged**
