### PR TITLE
patch allow program to stop correctly from halui and axisrc

### PR DESCRIPTION
**Pull request by alkabal**
Work fine

Now need to do something similar for button stop from GUI

### CODE REVIEW

**Comment by kiall** [comment]
1) What scenarios does this working with? I've tried it, but can't trigger it to stop.

2) I'm not sure mixing this into the error handling functions is the right thing to do - It probably needs a better place than in the error polling method (Stop or Abort aren't errors - just signals to react to!)

and .. 3) I believe we have much larger issues with the abort/stop/UI hanging that are going to need a large amount of code changes to get right - e.g. if you hit "Probe Tool Setter" when you're far away from the setter, there is no way (other than estop) to abort the movements.

Fixing this is likely to resolve the other issues around stopping / aborting - but again is a much bigger change, one I would like to wait until the codebase has been completely cleaned up before doing.

**Comment by alkabal** [comment]
This code work only if you have linked halui.abort and halui.program.stop to something 


For my own halui.program.stop is linked to my pendant 
And halui.abort is linked to my orient and spinload component 

I have put this in error checking because they allow to change nothing other in code and the stuff need to be like a error and stop all the process 

No problem for waiting and doing this in a way you think better !

**Comment by alkabal** [comment]
https://github.com/LinuxCNC/linuxcnc/pull/1013

**Comment by alkabal** [comment]
Hi

A modified axis.py seem to be not rejected for add abort and error pin, i have some trouble to reproduce your axisrc code inside axis, if you like the idea to include these pin to axis, can you help ?

Br

**Pull request closed without merging**
